# Generated by Django 3.1.4 on 2021-05-04 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0006_auto_20210504_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionaryline',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
