# Generated by Django 3.1.4 on 2021-05-04 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0007_auto_20210504_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionaryline',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
