# Generated by Django 3.1.4 on 2021-05-04 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0010_auto_20210504_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionaryline',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
