# Generated by Django 3.1.4 on 2021-05-10 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0012_auto_20210504_2046'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='New_user',
        ),
    ]
