# Generated by Django 3.1.4 on 2021-04-27 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_registration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='email',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='last_name',
        ),
    ]
